<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\WukongMp.Coop.Common\WukongMp.Coop.Common.csproj"/>
    </ItemGroup>

    <PropertyGroup>
        <UseSdkProjectReferences Condition="'$(UseSdkProjectReferences)' == ''">false</UseSdkProjectReferences>
        <SdkDllPath Condition="'$(SdkDllPath)' == ''">$(MSBuildThisFileDirectory)..\Dependencies\SDK</SdkDllPath>
        <LoaderDllPath Condition="'$(CoreDllPath)' == ''">$(MSBuildThisFileDirectory)..\Dependencies\Loader</LoaderDllPath>
    </PropertyGroup>

    <ItemGroup Condition="'$(UseSdkProjectReferences)' == 'true'">
        <ProjectReference Include="..\..\readym-gameserver\src\ReadyM.Api.Generators\ReadyM.Api.Generators.csproj" ReferenceOutputAssembly="true" OutputItemType="Analyzer"/>
        <ProjectReference Include="..\..\readym-gameserver\src\ReadyM.Relay.Server.Sdk\ReadyM.Relay.Server.Sdk.csproj" />
        <ProjectReference Include="..\..\readym-gameserver\src\ReadyM.Wukong.Common\ReadyM.Wukong.Common.csproj" />
    </ItemGroup>

</Project>
